# docker-compose.yml

version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
#Take note of the volumes. Without the anonymous volume ('/app/node_modules'), the node_modules directory would be overwritten by the mounting of the host directory at runtime. In other words, this would happen:

# Build - The node_modules directory is created in the image.
# Run - The current directory is mounted into the container, overwriting the  node_modules that were installed during the build.
